// Karl's GIR - PDF Export Utility
// Three read-only player exports: Round Report, Round Log, Career Report
// Uses jsPDF + jsPDF-AutoTable for clean typeset output

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Hole } from '@/types';
import { calculateRoundStats } from './stats';

// ─── Brand constants ──────────────────────────────────────────────────────────
const BRAND_GREEN = [52, 120, 52] as [number, number, number];
const BRAND_LIGHT = [230, 245, 220] as [number, number, number];
const TEXT_DARK   = [30, 40, 30]   as [number, number, number];
const TEXT_MID    = [80, 95, 80]   as [number, number, number];
const TEXT_MUTED  = [130, 145, 130] as [number, number, number];

// ─── Helpers ─────────────────────────────────────────────────────────────────

function toParStr(score: number, par: number): string {
  const d = score - par;
  return d === 0 ? 'E' : d > 0 ? `+${d}` : `${d}`;
}

function pct(n: number, d: number, decimals = 1): string {
  return d > 0 ? `${((n / d) * 100).toFixed(decimals)}%` : '—';
}

function formatFairway(fairway: unknown): string {
  if (fairway === null || fairway === undefined || fairway === 'na') return '—';
  if (fairway === 'y' || fairway === 'c') return 'Center';
  if (fairway === 'l') return 'Left';
  if (fairway === 'r') return 'Right';
  if (fairway === 'n') return 'Miss';
  if (fairway === 'rough') return 'Rough';
  if (fairway === 'sand') return 'Sand';
  return '—';
}

function header(doc: jsPDF, title: string, subtitle: string) {
  const W = doc.internal.pageSize.getWidth();

  // Green header bar
  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, 0, W, 20, 'F');

  // Logo text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Karl Golf GIR', 14, 13);

  // Title right-aligned
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(title, W - 14, 8, { align: 'right' });
  doc.text(subtitle, W - 14, 14, { align: 'right' });

  // Footer watermark function registered for each page
  return 22; // y start for content
}

function footer(doc: jsPDF) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setTextColor(...TEXT_MUTED);
  doc.setFont('helvetica', 'italic');
  doc.text(
    `Generated by Karl Golf GIR · karlgolf.app · ${new Date().toLocaleDateString()}`,
    W / 2,
    H - 6,
    { align: 'center' }
  );
}

function statRow(doc: jsPDF, label: string, value: string, benchmark: string | null, y: number): number {
  const W = doc.internal.pageSize.getWidth();
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...TEXT_MID);
  doc.text(label, 14, y);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEXT_DARK);
  doc.text(value, 90, y);
  if (benchmark) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.text(benchmark, W - 14, y, { align: 'right' });
  }
  return y + 7;
}

function sectionTitle(doc: jsPDF, text: string, y: number): number {
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND_GREEN);
  doc.text(text.toUpperCase(), 14, y);
  doc.setDrawColor(...BRAND_GREEN);
  doc.setLineWidth(0.3);
  doc.line(14, y + 1.5, doc.internal.pageSize.getWidth() - 14, y + 1.5);
  return y + 8;
}

// ─── 1. Round Report PDF ─────────────────────────────────────────────────────
// Full scorecard + stats for a single round

export function exportRoundReportPDF(
  holes: Hole[],
  courseName: string,
  date?: string
): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const dateStr = date ? new Date(date).toLocaleDateString() : new Date().toLocaleDateString();
  let y = header(doc, courseName, dateStr);

  // Course + date subtitle
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEXT_DARK);
  doc.text(`Round Report`, 14, y + 4);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...TEXT_MID);
  doc.text(`${courseName}  ·  ${dateStr}  ·  ${holes.length} holes`, 14, y + 10);
  y += 16;

  // ── Scorecard table ──
  const rows = holes.map(h => {
    return [
      String(h.holeNumber),
      String(h.par),
      String(h.score),
      toParStr(h.score, h.par),
      h.gir === 'y' ? '✓' : '✗',
      String(h.putts),
      h.par !== 3 ? formatFairway((h as any).fairway) : '—',
      h.proximity ? `${h.proximity}yd` : '—',
      (h as any).penaltyStrokes > 0 ? `+${(h as any).penaltyStrokes}` : '—',
    ];
  });

  // Totals row
  const stats = calculateRoundStats(holes);
  rows.push([
    'TOT',
    String(stats.totalPar),
    String(stats.totalScore),
    toParStr(stats.totalScore, stats.totalPar),
    `${stats.girsHit}/${stats.totalHoles}`,
    String(stats.totalPutts),
    `${stats.fairwaysHit}/${stats.eligibleFairways}`,
    stats.avgProximity ? `${Math.round(stats.avgProximity as number)}yd` : '—',
    String(stats.totalPenaltyStrokes ?? 0),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['#', 'Par', 'Score', '+/-', 'GIR', 'Putts', 'Fairway', 'Prox', 'Pen']],
    body: rows,
    theme: 'grid',
    styles: {
      fontSize: 8,
      cellPadding: 2.5,
      textColor: TEXT_DARK,
      lineColor: [200, 215, 200],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: BRAND_GREEN,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7.5,
    },
    footStyles: { fillColor: BRAND_LIGHT, fontStyle: 'bold' },
    columnStyles: {
      0: { halign: 'center', cellWidth: 10 },
      1: { halign: 'center', cellWidth: 12 },
      2: { halign: 'center', cellWidth: 14 },
      3: { halign: 'center', cellWidth: 14 },
      4: { halign: 'center', cellWidth: 12 },
      5: { halign: 'center', cellWidth: 13 },
      6: { halign: 'center', cellWidth: 22 },
      7: { halign: 'center', cellWidth: 18 },
      8: { halign: 'center', cellWidth: 14 },
    },
    // Highlight GIR column: green for hit, red-tinted for miss
    didParseCell(data) {
      if (data.section === 'body' && data.column.index === 4) {
        if (data.cell.raw === '✓') {
          data.cell.styles.textColor = [34, 120, 34];
          data.cell.styles.fontStyle = 'bold';
        } else if (data.cell.raw === '✗') {
          data.cell.styles.textColor = [180, 60, 60];
        }
      }
      // Bold totals row
      if (data.section === 'body' && data.row.index === rows.length - 1) {
        data.cell.styles.fillColor = BRAND_LIGHT;
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  // ── Stats summary ──
  y = (doc as any).lastAutoTable.finalY + 10;

  // New page if less than 80mm remaining
  if (y > doc.internal.pageSize.getHeight() - 80) {
    doc.addPage();
    header(doc, courseName, dateStr);
    y = 30;
  }

  y = sectionTitle(doc, 'Round Statistics', y);
  y = statRow(doc, 'GIR', `${stats.girsHit}/${stats.totalHoles}  (${pct(stats.girsHit, stats.totalHoles)})`, 'PGA Tour avg: 66%', y);
  y = statRow(doc, 'Fairways Hit', `${stats.fairwaysHit}/${stats.eligibleFairways}  (${pct(stats.fairwaysHit, stats.eligibleFairways)})`, 'PGA Tour avg: 62%', y);
  y = statRow(doc, 'Total Putts', `${stats.totalPutts}  (${(stats.avgPutts ?? 0).toFixed(2)}/hole)`, null, y);
  y = statRow(doc, 'Putts per GIR', (stats.puttsPerGIR ?? 0) > 0 ? (stats.puttsPerGIR as number).toFixed(2) : '—', 'PGA Tour avg: 1.77', y);
  y = statRow(doc, 'Scrambling', `${stats.scrambling}/${stats.missedGirs}  (${typeof stats.scramblingPercentage === 'number' ? stats.scramblingPercentage.toFixed(1) : stats.scramblingPercentage}%)`, 'of missed GIR', y);
  if ((stats.avgProximity ?? 0) > 0) {
    y = statRow(doc, 'Avg Approach Dist', `${Math.round(stats.avgProximity as number)} yd`, null, y);
  }
  if ((stats.totalPenaltyStrokes ?? 0) > 0) {
    y = statRow(doc, 'Penalty Strokes', String(stats.totalPenaltyStrokes), null, y);
  }

  footer(doc);

  const safe = courseName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  const d = date ? date.split('T')[0] : new Date().toISOString().split('T')[0];
  doc.save(`karls-gir_round-report_${safe}_${d}.pdf`);
}

// ─── 2. Round Log PDF ────────────────────────────────────────────────────────
// One row per round — full playing history

export function exportRoundLogPDF(rounds: any[]): void {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const today = new Date().toLocaleDateString();
  let y = header(doc, 'All Rounds', today);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEXT_DARK);
  doc.text('Round Log', 14, y + 4);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...TEXT_MID);
  doc.text(`${rounds.length} rounds  ·  most recent first`, 14, y + 10);
  y += 16;

  // Sort newest first
  const sorted = [...rounds].sort((a, b) => {
    const da = new Date(a.date ?? 0).getTime();
    const db = new Date(b.date ?? 0).getTime();
    return db - da;
  });

  const rows = sorted.map((r, i) => {
    const holes: Hole[] = r.holes ?? [];
    const stats = calculateRoundStats(holes);
    const dateStr = r.date ? new Date(r.date).toLocaleDateString() : '—';
    const toPar = stats.toPar;
    const toParDisplay = toPar === 0 ? 'E' : toPar > 0 ? `+${toPar}` : `${toPar}`;
    return [
      String(sorted.length - i),         // Round #
      dateStr,
      r.courseName ?? '—',
      String(stats.totalHoles),
      String(stats.totalScore),
      toParDisplay,
      `${pct(stats.girsHit, stats.totalHoles)}`,
      `${pct(stats.fairwaysHit, stats.eligibleFairways)}`,
      (stats.avgPutts ?? 0).toFixed(1),
      (stats.puttsPerGIR ?? 0) > 0 ? (stats.puttsPerGIR as number).toFixed(2) : '—',
      `${typeof stats.scramblingPercentage === 'number' ? stats.scramblingPercentage.toFixed(1) : stats.scramblingPercentage}%`,
    ];
  });

  autoTable(doc, {
    startY: y,
    head: [['#', 'Date', 'Course', 'Holes', 'Score', '+/-', 'GIR%', 'FW%', 'Putts', 'Putts/GIR', 'Scramble%']],
    body: rows,
    theme: 'striped',
    styles: {
      fontSize: 8,
      cellPadding: 2.5,
      textColor: TEXT_DARK,
    },
    headStyles: {
      fillColor: BRAND_GREEN,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7.5,
    },
    alternateRowStyles: { fillColor: [245, 250, 245] },
    columnStyles: {
      0:  { halign: 'center', cellWidth: 12 },
      1:  { halign: 'center', cellWidth: 24 },
      2:  { cellWidth: 55 },
      3:  { halign: 'center', cellWidth: 14 },
      4:  { halign: 'center', cellWidth: 16 },
      5:  { halign: 'center', cellWidth: 14 },
      6:  { halign: 'center', cellWidth: 18 },
      7:  { halign: 'center', cellWidth: 18 },
      8:  { halign: 'center', cellWidth: 16 },
      9:  { halign: 'center', cellWidth: 22 },
      10: { halign: 'center', cellWidth: 22 },
    },
  });

  footer(doc);
  doc.save(`karls-gir_round-log_${new Date().toISOString().split('T')[0]}.pdf`);
}

// ─── 3. Career Report PDF ────────────────────────────────────────────────────
// All-time averages + last 5 vs all-time trend + best round callout

export function exportCareerReportPDF(rounds: any[], cumulative: any): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const today = new Date().toLocaleDateString();
  let y = header(doc, 'Career Report', today);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEXT_DARK);
  doc.text('Career Performance Report', 14, y + 5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...TEXT_MID);
  doc.text(`${rounds.length} rounds tracked  ·  As of ${today}`, 14, y + 12);
  y += 20;

  // ── All-time stats ──
  y = sectionTitle(doc, 'All-Time Averages', y);
  y = statRow(doc, 'Rounds Played',     String(rounds.length), null, y);
  y = statRow(doc, 'Total Holes',       String(cumulative.totalHoles ?? '—'), null, y);
  y = statRow(doc, 'GIR %',             `${(cumulative.girPct ?? 0).toFixed(1)}%`, 'PGA Tour: 66.0%', y);
  y = statRow(doc, 'Fairways %',        `${(cumulative.fairwayPct ?? 0).toFixed(1)}%`, 'PGA Tour: 62.0%', y);
  y = statRow(doc, 'Avg Putts / Hole',  `${(cumulative.avgPutts ?? 0).toFixed(2)}`, 'PGA Tour: 1.77', y);
  y = statRow(doc, 'Putts / GIR',       (cumulative.puttsPerGIR ?? 0) > 0 ? (cumulative.puttsPerGIR).toFixed(2) : '—', 'PGA Tour: 1.77', y);
  y = statRow(doc, 'Scrambling %',      `${(cumulative.scramblingPct ?? 0).toFixed(1)}%`, 'of missed GIR  ·  PGA Tour: 58%', y);
  if ((cumulative.avgProximity ?? 0) > 0) {
    y = statRow(doc, 'Avg Approach Dist', `${Math.round(cumulative.avgProximity)} yd`, null, y);
  }
  y += 4;

  // ── Last 5 vs all-time trend ──
  const completed = rounds.filter(r => r.isComplete && (r.holes?.length ?? 0) >= 9);
  const last5 = completed.slice(-5);

  if (last5.length >= 2) {
    y = sectionTitle(doc, `Last ${last5.length} Rounds vs All-Time`, y);

    const l5holes = last5.flatMap(r => r.holes ?? []) as Hole[];
    const l5stats = calculateRoundStats(l5holes);

    const trendRows = [
      ['GIR %',
        `${pct(l5stats.girsHit, l5stats.totalHoles)}`,
        `${(cumulative.girPct ?? 0).toFixed(1)}%`,
        trendArrow(l5stats.girsHit / l5stats.totalHoles, (cumulative.girPct ?? 0) / 100, true)],
      ['Fairways %',
        `${pct(l5stats.fairwaysHit, l5stats.eligibleFairways)}`,
        `${(cumulative.fairwayPct ?? 0).toFixed(1)}%`,
        trendArrow(l5stats.fairwaysHit / l5stats.eligibleFairways, (cumulative.fairwayPct ?? 0) / 100, true)],
      ['Avg Putts',
        `${(l5stats.avgPutts ?? 0).toFixed(2)}`,
        `${(cumulative.avgPutts ?? 0).toFixed(2)}`,
        trendArrow(l5stats.avgPutts ?? 0, cumulative.avgPutts ?? 0, false)],
      ['Putts/GIR',
        (l5stats.puttsPerGIR ?? 0) > 0 ? (l5stats.puttsPerGIR as number).toFixed(2) : '—',
        (cumulative.puttsPerGIR ?? 0) > 0 ? (cumulative.puttsPerGIR).toFixed(2) : '—',
        (l5stats.puttsPerGIR ?? 0) > 0 ? trendArrow(l5stats.puttsPerGIR as number, cumulative.puttsPerGIR ?? 0, false) : ''],
      ['Scrambling %',
        `${typeof l5stats.scramblingPercentage === 'number' ? l5stats.scramblingPercentage.toFixed(1) : l5stats.scramblingPercentage}%`,
        `${(cumulative.scramblingPct ?? 0).toFixed(1)}%`,
        trendArrow(
          typeof l5stats.scramblingPercentage === 'number' ? l5stats.scramblingPercentage / 100 : 0,
          (cumulative.scramblingPct ?? 0) / 100,
          true
        )],
    ];

    autoTable(doc, {
      startY: y,
      head: [['Metric', `Last ${last5.length} Rounds`, 'All-Time', 'Trend']],
      body: trendRows,
      theme: 'grid',
      styles: { fontSize: 8.5, cellPadding: 3, textColor: TEXT_DARK },
      headStyles: { fillColor: BRAND_GREEN, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 50 },
        1: { halign: 'center', cellWidth: 40 },
        2: { halign: 'center', cellWidth: 40 },
        3: { halign: 'center', cellWidth: 30 },
      },
      didParseCell(data) {
        if (data.section === 'body' && data.column.index === 3) {
          const v = String(data.cell.raw);
          if (v.includes('▲')) data.cell.styles.textColor = [34, 120, 34];
          if (v.includes('▼')) data.cell.styles.textColor = [180, 60, 60];
        }
      },
    });

    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // ── Best round callout ──
  if (completed.length > 0) {
    const best = completed.reduce((best, r) => {
      const s = calculateRoundStats(r.holes ?? []);
      const bestS = calculateRoundStats(best.holes ?? []);
      // Best = highest GIR% (ties broken by lowest to-par)
      const girA = s.girsHit / (s.totalHoles || 1);
      const girB = bestS.girsHit / (bestS.totalHoles || 1);
      return girA > girB || (girA === girB && s.toPar < bestS.toPar) ? r : best;
    });
    const bs = calculateRoundStats(best.holes ?? []);
    const bestDate = best.date ? new Date(best.date).toLocaleDateString() : '—';

    if (y > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      header(doc, 'Career Report', today);
      y = 30;
    }

    y = sectionTitle(doc, 'Best Round (by GIR)', y);
    doc.setFillColor(...BRAND_LIGHT);
    doc.roundedRect(14, y - 2, doc.internal.pageSize.getWidth() - 28, 28, 2, 2, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...TEXT_DARK);
    doc.text(best.courseName ?? '—', 18, y + 5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...TEXT_MID);
    doc.setFontSize(8);
    doc.text(bestDate, 18, y + 11);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND_GREEN);
    doc.text(`GIR: ${pct(bs.girsHit, bs.totalHoles)}`, 18, y + 18);
    doc.setTextColor(...TEXT_DARK);
    doc.text(`Score: ${bs.totalScore}  (${toParStr(bs.totalScore, bs.totalPar)})`, 70, y + 18);
    doc.text(`Putts: ${bs.totalPutts}`, 130, y + 18);
  }

  footer(doc);
  doc.save(`karls-gir_career-report_${new Date().toISOString().split('T')[0]}.pdf`);
}

// ─── Trend arrow helper ───────────────────────────────────────────────────────
// higherIsBetter: true for GIR%, FW%, Scrambling; false for putts
function trendArrow(recent: number, allTime: number, higherIsBetter: boolean): string {
  if (!isFinite(recent) || !isFinite(allTime)) return '—';
  const delta = recent - allTime;
  const threshold = 0.005; // 0.5% noise floor
  if (Math.abs(delta) < threshold) return '→ same';
  const improving = higherIsBetter ? delta > 0 : delta < 0;
  return improving ? '▲ improving' : '▼ declining';
}
